import type { Lead } from "@/lib/types"

// Mock data - only closed leads (clients)
export const mockClients: Lead[] = [
  {
    id: "1",
    name: "Roberto Alves",
    company: "Enterprise Corp",
    email: "roberto@enterprise.com",
    phone: "+55 11 98765-4321",
    cpfCnpj: "12.345.678/0001-90",
    location: "São Paulo, SP",
    status: "fechado",
    assignedCloser: "Julia Ferreira",
    linkedin: "https://linkedin.com/in/robertoalves",
    value: 45000,
    notes: "Cliente fechou contrato anual. Implementação prevista para fevereiro.",
    createdAt: "2025-01-05",
  },
  {
    id: "2",
    name: "Fernanda Lima",
    company: "Global Services",
    email: "fernanda@globalservices.com",
    phone: "+55 61 99876-5432",
    cpfCnpj: "98.765.432/0001-10",
    location: "Brasília, DF",
    status: "fechado",
    assignedCloser: "Ricardo Souza",
    linkedin: "https://linkedin.com/in/fernandalima",
    instagram: "https://instagram.com/globalservices",
    value: 78000,
    notes: "Contrato de 2 anos. Cliente solicitou treinamento personalizado.",
    createdAt: "2025-01-04",
  },
  {
    id: "3",
    name: "Carlos Mendes",
    company: "Tech Innovations",
    email: "carlos@techinnovations.com",
    phone: "+55 21 97654-3210",
    cpfCnpj: "11.222.333/0001-44",
    location: "Rio de Janeiro, RJ",
    status: "fechado",
    assignedCloser: "Julia Ferreira",
    linkedin: "https://linkedin.com/in/carlosmendes",
    value: 120000,
    notes: "Maior contrato do trimestre. Inclui suporte premium 24/7.",
    createdAt: "2025-01-02",
  },
]
